/**
 * 更新
 */
export const UPDATE_WORD = 'UPDATE_WORD';
/**
 * 翻訳
 */
export const TRANSLATE_WORD = 'TRANSLATE_WORD';
export const TRANSLATE_WORD_START = 'TRANSLATE_WORD_START';
export const TRANSLATE_WORD_SUCCEEDED = 'TRANSLATE_WORD_SUCCEEDED';
export const TRANSLATE_WORD_FAILED = 'TRANSLATE_WORD_FAILED';
/**
 * 単語選択
 */
export const SELECT_WORD = 'SELECT_WORD';

// fetch dictionary
export const FETCH_DICTIONARY_REQUESTED = 'FETCH_DICTIONARY_REQUESTED';
export const FETCH_DICTIONARY_START = 'FETCH_DICTIONARY_START';
export const FETCH_DICTIONARY_SUCCEEDED = 'FETCH_DICTIONARY_SUCCEEDED';
export const FETCH_DICTIONARY_FAILED = 'FETCH_DICTIONARY_FAILED';
